# Generated by Django 6.0 on 2025-12-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('light_requirements', models.CharField(choices=[('low', 'Low Light'), ('medium', 'Medium Light'), ('bright', 'Bright Light'), ('direct', 'Direct Sunlight')], default='medium', max_length=10)),
                ('water_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('soil_type', models.CharField(default='Well-draining potting mix', max_length=200)),
                ('temperature_range', models.CharField(default='18-24°C (65-75°F)', max_length=100)),
                ('humidity', models.CharField(default='40-60%', max_length=100)),
                ('care_instructions', models.TextField(help_text='Detailed care instructions')),
                ('common_problems', models.TextField(blank=True, help_text='Common problems and solutions')),
                ('fertilizer_needs', models.CharField(default='Monthly during growing season', max_length=200)),
                ('repotting_frequency', models.CharField(default='Every 1-2 years', max_length=100)),
                ('mature_size', models.CharField(blank=True, max_length=100)),
                ('growth_rate', models.CharField(default='Medium', max_length=50)),
                ('pet_safe', models.BooleanField(default=False)),
                ('air_purifying', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
