# Generated by Django 6.0 on 2025-12-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of plant image', max_length=500, null=True),
        ),
    ]
