# Generated by Django 6.0.3 on 2026-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_herbal',
            field=models.BooleanField(default=False, help_text='Herb / medicinal plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='is_indoor',
            field=models.BooleanField(default=False, help_text='Suitable for indoor growing'),
        ),
    ]
