# Generated by Django 6.0.3 on 2026-04-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_is_herbal_plant_is_indoor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Stressed', 'Stressed'), ('Diseased', 'Diseased'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('current_condition', models.TextField(blank=True)),
                ('care_plan', models.JSONField(default=dict)),
                ('cure_plan', models.TextField(blank=True, null=True)),
                ('common_problems', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='analyses/')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
