# Generated by Django 6.0.3 on 2026-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_plantanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalysis',
            name='severity_score',
            field=models.PositiveSmallIntegerField(default=5, help_text='1 (thriving) – 10 (critical)'),
        ),
    ]
