from django.core.management.base import BaseCommand
from plants.models import Plant


class Command(BaseCommand):
    help = 'Populate the database with real-world plants'

    def handle(self, *args, **options):
        plants_data = [
            {
                'name': 'Snake Plant',
                'scientific_name': 'Sansevieria trifasciata',
                'description': 'A hardy, low-maintenance plant perfect for beginners. Known for its striking upright leaves with yellow edges.',
                'difficulty': 'easy',
                'light_requirements': 'low',
                'water_frequency': 'biweekly',
                'soil_type': 'Well-draining cactus mix',
                'temperature_range': '15-27°C (60-80°F)',
                'humidity': '30-50%',
                'care_instructions': 'Water only when soil is completely dry. Can tolerate neglect and low light conditions. Avoid overwatering as this can cause root rot.',
                'common_problems': 'Overwatering leads to root rot. Brown tips indicate low humidity or fluoride in water. Use filtered water if possible.',
                'fertilizer_needs': 'Light feeding 2-3 times during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '2-4 feet tall',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': True,
                'featured': True,
            },
            {
                'name': 'Pothos',
                'scientific_name': 'Epipremnum aureum',
                'description': 'A trailing vine with heart-shaped leaves, perfect for hanging baskets or climbing up moss poles.',
                'difficulty': 'easy',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Regular potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Can grow in water or soil. Pinch back to encourage bushier growth.',
                'common_problems': 'Yellow leaves indicate overwatering. Brown leaf tips suggest low humidity or underwatering.',
                'fertilizer_needs': 'Monthly during spring and summer',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-10 feet long',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': True,
                'featured': True,
            },
            {
                'name': 'Spider Plant',
                'scientific_name': 'Chlorophytum comosum',
                'description': 'A cheerful plant with arching green and white striped leaves that produces baby plantlets.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-60%',
                'care_instructions': 'Keep soil evenly moist but not soggy. Produces plantlets that can be propagated easily.',
                'common_problems': 'Brown leaf tips from dry air or fluoride in water. Use distilled water if possible.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '12-18 inches',
                'growth_rate': 'Fast',
                'pet_safe': True,
                'air_purifying': True,
                'featured': True,
            },
            {
                'name': 'Monstera Deliciosa',
                'scientific_name': 'Monstera deliciosa',
                'description': 'A stunning tropical plant known for its large, split leaves. A true statement piece for any home.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix with perlite',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-80%',
                'care_instructions': 'Provide bright, indirect light and high humidity. Support with a moss pole for best growth.',
                'common_problems': 'Lack of splits in leaves indicates insufficient light. Yellow leaves suggest overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': True,
            },
            {
                'name': 'Peace Lily',
                'scientific_name': 'Spathiphyllum wallisii',
                'description': 'An elegant plant with dark green leaves and beautiful white flowers that bloom periodically.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '50-70%',
                'care_instructions': 'Keep soil consistently moist but not waterlogged. Drooping leaves indicate need for water.',
                'common_problems': 'Brown leaf tips from low humidity or fluoride. Yellow leaves indicate overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '1-3 feet',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': True,
            },
            {
                'name': 'Rubber Plant',
                'scientific_name': 'Ficus elastica',
                'description': 'A classic houseplant with large, glossy leaves that can grow into an impressive indoor tree.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '40-60%',
                'care_instructions': 'Wipe leaves regularly to keep them glossy. Rotate plant for even growth.',
                'common_problems': 'Leaf drop from overwatering or sudden environmental changes. Sticky sap is normal.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-10 feet indoors',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
        ]

        # Add remaining 34 plants
        additional_plants = [
            {
                'name': 'ZZ Plant',
                'scientific_name': 'Zamioculcas zamiifolia',
                'description': 'An extremely low-maintenance plant with waxy, dark green leaves. Perfect for low-light areas.',
                'difficulty': 'easy',
                'light_requirements': 'low',
                'water_frequency': 'monthly',
                'soil_type': 'Well-draining cactus mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '30-50%',
                'care_instructions': 'Water very sparingly. Can survive in very low light and with minimal care.',
                'common_problems': 'Overwatering is the main issue. Yellow leaves indicate too much water.',
                'fertilizer_needs': '2-3 times per year',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '2-3 feet',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Fiddle Leaf Fig',
                'scientific_name': 'Ficus lyrata',
                'description': 'A trendy plant with large, violin-shaped leaves. Requires more attention but makes a stunning focal point.',
                'difficulty': 'hard',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '50-70%',
                'care_instructions': 'Needs consistent care and bright, indirect light. Avoid moving frequently.',
                'common_problems': 'Brown spots from overwatering. Leaf drop from environmental stress or inconsistent watering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-10 feet indoors',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Aloe Vera',
                'scientific_name': 'Aloe barbadensis miller',
                'description': 'A succulent plant known for its medicinal properties and thick, fleshy leaves.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Cactus and succulent mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '30-40%',
                'care_instructions': 'Water deeply but infrequently. Allow soil to dry completely between waterings.',
                'common_problems': 'Root rot from overwatering. Brown leaf tips from too much direct sun.',
                'fertilizer_needs': 'Light feeding 2-3 times per year',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '1-2 feet',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Boston Fern',
                'scientific_name': 'Nephrolepis exaltata',
                'description': 'A lush, feathery fern that adds a tropical feel to any space.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Peat-based potting mix',
                'temperature_range': '16-24°C (60-75°F)',
                'humidity': '60-80%',
                'care_instructions': 'Keep soil consistently moist and provide high humidity. Mist regularly.',
                'common_problems': 'Brown fronds from low humidity or underwatering. Scale insects can be an issue.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '2-3 feet wide',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Philodendron Heartleaf',
                'scientific_name': 'Philodendron hederaceum',
                'description': 'A fast-growing vine with heart-shaped leaves, perfect for beginners.',
                'difficulty': 'easy',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Can trail or climb with support.',
                'common_problems': 'Yellow leaves from overwatering. Leggy growth in low light.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '4-6 feet long',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
        ]

        # Combine all plants
        all_plants = plants_data + additional_plants

        # Add more plants to reach 40
        more_plants = [
            {
                'name': 'Dracaena Marginata',
                'scientific_name': 'Dracaena marginata',
                'description': 'A striking plant with thin, arching leaves edged in red, resembling a small palm tree.',
                'difficulty': 'easy',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-50%',
                'care_instructions': 'Allow soil to dry between waterings. Remove dead leaves regularly.',
                'common_problems': 'Brown leaf tips from fluoride in water or low humidity.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Jade Plant',
                'scientific_name': 'Crassula ovata',
                'description': 'A popular succulent with thick, glossy leaves and tree-like growth pattern.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Cactus and succulent mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '30-40%',
                'care_instructions': 'Water deeply but infrequently. Provide bright light for compact growth.',
                'common_problems': 'Soft, mushy leaves from overwatering. Leggy growth in low light.',
                'fertilizer_needs': 'Light feeding during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '3-6 feet',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'English Ivy',
                'scientific_name': 'Hedera helix',
                'description': 'A classic trailing plant with distinctive lobed leaves, excellent for hanging baskets.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '16-21°C (60-70°F)',
                'humidity': '50-70%',
                'care_instructions': 'Keep soil evenly moist. Prefers cooler temperatures and good air circulation.',
                'common_problems': 'Spider mites in dry conditions. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-8 feet long',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Calathea Orbifolia',
                'scientific_name': 'Calathea orbifolia',
                'description': 'A stunning prayer plant with large, round leaves featuring silver and green stripes.',
                'difficulty': 'hard',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining, peat-based mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '60-80%',
                'care_instructions': 'Requires high humidity and filtered water. Leaves fold up at night.',
                'common_problems': 'Brown leaf edges from low humidity or tap water. Spider mites in dry conditions.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '2-3 feet',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Bird of Paradise',
                'scientific_name': 'Strelitzia reginae',
                'description': 'A dramatic tropical plant with large paddle-shaped leaves and exotic orange and blue flowers.',
                'difficulty': 'hard',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-70%',
                'care_instructions': 'Needs bright light and high humidity. Rotate regularly for even growth.',
                'common_problems': 'Split leaves are natural. Brown leaf tips from low humidity or underwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Pilea Peperomioides',
                'scientific_name': 'Pilea peperomioides',
                'description': 'Also known as Chinese Money Plant, features round, coin-shaped leaves on delicate stems.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Rotate weekly for even growth.',
                'common_problems': 'Curling leaves from too much direct sun. Dropping leaves from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '12 inches',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Anthurium',
                'scientific_name': 'Anthurium andraeanum',
                'description': 'A tropical plant known for its glossy, heart-shaped red flowers and dark green leaves.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining, chunky mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-80%',
                'care_instructions': 'Needs bright, indirect light and high humidity. Keep soil evenly moist.',
                'common_problems': 'Brown leaf tips from low humidity. Root rot from poor drainage.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '1-2 feet',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Hoya Carnosa',
                'scientific_name': 'Hoya carnosa',
                'description': 'A waxy-leaved vine that produces clusters of fragrant, star-shaped flowers.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining, chunky mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '40-60%',
                'care_instructions': 'Allow soil to dry between waterings. Provide bright light for flowering.',
                'common_problems': 'Dropping leaves from overwatering. No flowers without adequate light.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet long',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Schefflera',
                'scientific_name': 'Schefflera actinophylla',
                'description': 'An umbrella-shaped plant with glossy, palmate leaves arranged in clusters.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Pinch back to maintain shape.',
                'common_problems': 'Leaf drop from overwatering or low light. Scale insects can be problematic.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Croton',
                'scientific_name': 'Codiaeum variegatum',
                'description': 'A colorful plant with variegated leaves in shades of yellow, orange, red, and green.',
                'difficulty': 'hard',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '50-70%',
                'care_instructions': 'Needs bright light to maintain colorful foliage. Keep soil evenly moist.',
                'common_problems': 'Leaf drop from environmental stress. Loss of color in low light.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '3-6 feet',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Parlor Palm',
                'scientific_name': 'Chamaedorea elegans',
                'description': 'A small, elegant palm that thrives in low light conditions and adds tropical flair.',
                'difficulty': 'easy',
                'light_requirements': 'low',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '50-60%',
                'care_instructions': 'Keep soil evenly moist but not soggy. Tolerates low light well.',
                'common_problems': 'Brown leaf tips from low humidity or fluoride in water.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '4-6 feet',
                'growth_rate': 'Slow',
                'pet_safe': True,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Dieffenbachia',
                'scientific_name': 'Dieffenbachia seguine',
                'description': 'A tropical plant with large, variegated leaves featuring green and cream patterns.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '50-60%',
                'care_instructions': 'Keep soil evenly moist. Wipe leaves regularly to maintain appearance.',
                'common_problems': 'Leaf drop from cold drafts. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '3-6 feet',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Alocasia Amazonica',
                'scientific_name': 'Alocasia amazonica',
                'description': 'A striking plant with dark green, arrow-shaped leaves and prominent white veins.',
                'difficulty': 'hard',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining, chunky mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-80%',
                'care_instructions': 'Requires high humidity and consistent moisture. Avoid cold drafts.',
                'common_problems': 'Leaf drop from low humidity or temperature fluctuations.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '2-3 feet',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Yucca',
                'scientific_name': 'Yucca elephantipes',
                'description': 'A drought-tolerant plant with sword-like leaves and a thick, woody stem.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Well-draining cactus mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '30-40%',
                'care_instructions': 'Water deeply but infrequently. Provide bright light for best growth.',
                'common_problems': 'Root rot from overwatering. Brown leaf tips from low humidity.',
                'fertilizer_needs': 'Light feeding during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Tradescantia Zebrina',
                'scientific_name': 'Tradescantia zebrina',
                'description': 'A fast-growing trailing plant with purple and silver striped leaves.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Pinch back to encourage bushiness.',
                'common_problems': 'Leggy growth in low light. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-8 inches tall, trailing',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Peperomia Obtusifolia',
                'scientific_name': 'Peperomia obtusifolia',
                'description': 'A compact plant with thick, glossy leaves, perfect for small spaces.',
                'difficulty': 'easy',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-50%',
                'care_instructions': 'Water when top inch of soil is dry. Avoid overwatering.',
                'common_problems': 'Root rot from overwatering. Leaf drop from cold temperatures.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '8-12 inches',
                'growth_rate': 'Slow',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Aglaonema',
                'scientific_name': 'Aglaonema commutatum',
                'description': 'A colorful foliage plant with patterned leaves in shades of green, pink, and red.',
                'difficulty': 'easy',
                'light_requirements': 'low',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '50-60%',
                'care_instructions': 'Tolerates low light well. Keep soil evenly moist but not soggy.',
                'common_problems': 'Brown leaf tips from fluoride in water. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '1-3 feet',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Maranta Leuconeura',
                'scientific_name': 'Maranta leuconeura',
                'description': 'A prayer plant with beautiful patterned leaves that fold up at night.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining, peat-based mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '60-70%',
                'care_instructions': 'Needs high humidity and filtered water. Leaves move throughout the day.',
                'common_problems': 'Brown leaf edges from low humidity or tap water.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '12 inches',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Haworthia',
                'scientific_name': 'Haworthia fasciata',
                'description': 'A small succulent with distinctive white stripes on thick, pointed leaves.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Cactus and succulent mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '30-40%',
                'care_instructions': 'Water sparingly and provide bright, indirect light.',
                'common_problems': 'Root rot from overwatering. Stretching in low light.',
                'fertilizer_needs': 'Light feeding 2-3 times per year',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '4-6 inches',
                'growth_rate': 'Slow',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Fittonia',
                'scientific_name': 'Fittonia albivenis',
                'description': 'A small plant with intricate white or pink veined leaves, perfect for terrariums.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '60-80%',
                'care_instructions': 'Needs high humidity and consistent moisture. Dramatic when thirsty.',
                'common_problems': 'Wilting from underwatering. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6 inches',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Monstera Adansonii',
                'scientific_name': 'Monstera adansonii',
                'description': 'A climbing plant with distinctive holes in its leaves, known as Swiss Cheese Plant.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-70%',
                'care_instructions': 'Provide support for climbing. Keep soil evenly moist.',
                'common_problems': 'Yellow leaves from overwatering. Small holes indicate insufficient light.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-8 feet long',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': True,
                'featured': False,
            },
            {
                'name': 'Cactus Prickly Pear',
                'scientific_name': 'Opuntia microdasys',
                'description': 'A distinctive cactus with flat, paddle-shaped segments covered in small spines.',
                'difficulty': 'easy',
                'light_requirements': 'direct',
                'water_frequency': 'monthly',
                'soil_type': 'Cactus and succulent mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '20-30%',
                'care_instructions': 'Water very sparingly. Provide maximum light possible.',
                'common_problems': 'Root rot from overwatering. Etiolation in low light.',
                'fertilizer_needs': 'Light feeding 2-3 times per year',
                'repotting_frequency': 'Every 3-4 years',
                'mature_size': '2-3 feet',
                'growth_rate': 'Slow',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Begonia Rex',
                'scientific_name': 'Begonia rex-cultorum',
                'description': 'A stunning foliage plant with colorful, textured leaves in various patterns.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '50-70%',
                'care_instructions': 'Keep soil evenly moist but not soggy. Avoid getting water on leaves.',
                'common_problems': 'Powdery mildew from poor air circulation. Root rot from overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '12-18 inches',
                'growth_rate': 'Medium',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Ponytail Palm',
                'scientific_name': 'Beaucarnea recurvata',
                'description': 'A unique plant with a bulbous base and long, thin leaves that cascade like a ponytail.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Well-draining cactus mix',
                'temperature_range': '18-27°C (65-80°F)',
                'humidity': '30-40%',
                'care_instructions': 'Water deeply but infrequently. The bulbous base stores water.',
                'common_problems': 'Root rot from overwatering. Brown leaf tips from low humidity.',
                'fertilizer_needs': 'Light feeding during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Slow',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Norfolk Island Pine',
                'scientific_name': 'Araucaria heterophylla',
                'description': 'A symmetrical evergreen tree that makes an excellent living Christmas tree.',
                'difficulty': 'medium',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '16-21°C (60-70°F)',
                'humidity': '50-60%',
                'care_instructions': 'Keep soil evenly moist. Prefers cooler temperatures and high humidity.',
                'common_problems': 'Brown needles from low humidity or overwatering.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '6-8 feet indoors',
                'growth_rate': 'Slow',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'String of Hearts',
                'scientific_name': 'Ceropegia woodii',
                'description': 'A trailing succulent with heart-shaped leaves on thin, purple stems.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'biweekly',
                'soil_type': 'Well-draining succulent mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-50%',
                'care_instructions': 'Water when soil is dry. Provide bright, indirect light.',
                'common_problems': 'Root rot from overwatering. Leggy growth in low light.',
                'fertilizer_needs': 'Light feeding during growing season',
                'repotting_frequency': 'Every 2-3 years',
                'mature_size': '3-4 feet long',
                'growth_rate': 'Medium',
                'pet_safe': True,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Oxalis Triangularis',
                'scientific_name': 'Oxalis triangularis',
                'description': 'A charming plant with purple, triangular leaves that fold at night like butterflies.',
                'difficulty': 'easy',
                'light_requirements': 'bright',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '18-24°C (65-75°F)',
                'humidity': '40-60%',
                'care_instructions': 'Water when top inch of soil is dry. Leaves close at night.',
                'common_problems': 'Dormancy periods are normal. Overwatering can cause bulb rot.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '6-12 inches',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
            {
                'name': 'Caladium',
                'scientific_name': 'Caladium bicolor',
                'description': 'A tropical plant with large, colorful heart-shaped leaves in pink, white, and green.',
                'difficulty': 'medium',
                'light_requirements': 'medium',
                'water_frequency': 'weekly',
                'soil_type': 'Well-draining potting mix',
                'temperature_range': '20-27°C (68-80°F)',
                'humidity': '60-70%',
                'care_instructions': 'Keep soil evenly moist. Goes dormant in winter.',
                'common_problems': 'Leaf burn from direct sun. Natural dormancy in cooler months.',
                'fertilizer_needs': 'Monthly during growing season',
                'repotting_frequency': 'Every 1-2 years',
                'mature_size': '1-2 feet',
                'growth_rate': 'Fast',
                'pet_safe': False,
                'air_purifying': False,
                'featured': False,
            },
        ]

        # Combine all plants to get exactly 40
        all_plants = plants_data + additional_plants + more_plants

        for plant_data in all_plants:
            plant, created = Plant.objects.get_or_create(
                name=plant_data['name'],
                defaults=plant_data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f'Successfully created plant: {plant.name}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Plant already exists: {plant.name}')
                )

        self.stdout.write(
            self.style.SUCCESS(f'Successfully populated plants database with {len(all_plants)} real plants!')
        )